#!/usr/bin/env bash

# Times the screen off and puts it to background
swayidle \
    timeout  300 'swaymsg "output * power off"' \
    resume 'swaymsg "output * power on"' &
# Locks the screen immediately
sleep 0.5
swaylock --clock --indicator --effect-blur 7x5 --image ~/Pictures/wallpaper.jpg
# Kills last background task so idle timer doesn't keep running
kill %%
