#!/usr/bin/env bash

CONFIG=$HOME/.config/sway/wofi/config
STYLE=$HOME/.config/sway/wofi/style.css
COLOR=$HOME/.config/sway/wofi/colors


if [[ ! $(pidof wofi) ]]; then
	$menu wofi --show drun --prompt 'Search...' --conf ${CONFIG} --style ${STYLE} --color ${COLOR}
else
	pkill wofi
fi
